// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1VZwH22ev2dMYTtZ9law0bMF0a0MN5YA',
    appId: '1:915041923530:web:e0c873f668e09b31eddf33',
    messagingSenderId: '915041923530',
    projectId: 'noters-flutter',
    authDomain: 'noters-flutter.firebaseapp.com',
    storageBucket: 'noters-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfGkeB8E58rGn4FWxwmB0CGL--XJ6-P4',
    appId: '1:915041923530:android:c5d360e180d4f2a8eddf33',
    messagingSenderId: '915041923530',
    projectId: 'noters-flutter',
    storageBucket: 'noters-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_odclVwU7TOj3XPWT17ilTmheExle0Zc',
    appId: '1:915041923530:ios:024b4c0092476ca9eddf33',
    messagingSenderId: '915041923530',
    projectId: 'noters-flutter',
    storageBucket: 'noters-flutter.appspot.com',
    iosClientId: '915041923530-av5bb585919j42lk9p8nthojdbd4hb21.apps.googleusercontent.com',
    iosBundleId: 'com.chetankandala2023.noters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_odclVwU7TOj3XPWT17ilTmheExle0Zc',
    appId: '1:915041923530:ios:024b4c0092476ca9eddf33',
    messagingSenderId: '915041923530',
    projectId: 'noters-flutter',
    storageBucket: 'noters-flutter.appspot.com',
    iosClientId: '915041923530-av5bb585919j42lk9p8nthojdbd4hb21.apps.googleusercontent.com',
    iosBundleId: 'com.chetankandala2023.noters',
  );
}
